#! /usr/env/python
# A way to get the number of revisions in git
# The number of revisions is what we use as a version number, divided by 100
import subprocess

version = subprocess.Popen(['git', 'rev-list', 'HEAD', '--count'], stdout=subprocess.PIPE)
version = version.communicate()[0].decode()

try:
    version = '{0:06.2f}'.format(int(version)/100)
except:
    version = 'NOGIT'

fout = open('lib/version.py', 'w')
fout.write("### AUTOGENERATED FILE ###\n")
fout.write("version = '{}'\n".format(version))
fout.close()

print("Updated version.py to version", version)
