# A way to get the number of revisions in git
# The number of revisions is what we use as a version number, divided by 100
import subprocess

version = subprocess.Popen(['git', 'rev-list', 'HEAD', '--count'], stdout=subprocess.PIPE)
vtext = version.communicate()[0].decode()
vnum = 0

try:
    vnum = int(vtext)/100
except:
    -99.99          # Max negative version

fout = open('lib/version.py', 'w')
fout.write("### AUTOGENERATED FILE ###\n")
fout.write('version = ' + str(vnum) + '\n')
fout.close()

print("Updated version.py to version", vnum)
